Added missing string delimiter.
Even though this code isn't compiled, it was causing my build to fail with
this error:

CC      palacios/src/palacios/svm.o
palacios/src/palacios/svm.c:574:54: error: missing terminating " character